# Generated by Django 5.1.3 on 2024-11-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='about',
            name='image2',
            field=models.ImageField(default=1, upload_to='about/'),
            preserve_default=False,
        ),
    ]
